site_name: OpenStack Data Plane Operator
site_description: OpenStack Data Plane Operator
site_author: OpenStack Team
site_url: https://openstack-k8s-operators.github.io/dataplane-operator
repo_name: openstack-k8s-operators/dataplane-operator
repo_url: https://github.com/openstack-k8s-operators/dataplane-operator
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
  name: material
  logo: images/openstack-logo.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Custom Resources:
      - OpenStackDataPlaneNode: openstack_dataplanenode.md
      - OpenStackDataPlaneRole: openstack_dataplanerole.md
      - Inheritance: inheritance.md
  - Architecture: architecture.md
  - Contributing: contributing.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - admonition
extra:
  version:
    provider: mike
    default: latest
plugins:
  - git-revision-date
  - build_plantuml:
      diagram_root: "docs/diagrams"
      output_format: "svg"
  - search:
      lang: en
      prebuild_index: true
